version: "3"
services:
  backend:
    container_name: backend-prod
    image: back_prod:build_${BUILD_NUMBER}
    build:
      context: .
      args:
        - WAR_FILE=target/tasks-backend.war
        - CONTEXT=tasks-backend
    networks:
      - prod_net_back
      - prod_net_front
    #ports:
    #  - 9998:8080
    environment:
      - DATABASE_HOST=192.168.1.168
      - DATABASE_PORT=3309
      - DATABASE_USER=root
      - DATABASE_PASSWD=root
      #- DATABASE_UPDATE=none


  frontend:
    container_name: frontend-prod
    image: front_prod:build_${BUILD_NUMBER}
    build:
        context: .
        args:
          - WAR_FILE=frontend/target/tasks.war
          - CONTEXT=tasks
    networks:
      - prod_net_front
    ports:
      - 9999:8080
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8080
      - APP_VERSION=build_${BUILD_NUMBER}
    #depends_on:
    #  - backend

networks:
  prod_net_front:
  prod_net_back:
